### PR TITLE
Address twin_column_name error in time series histogram plotting

### PR DESCRIPTION
**Pull request by fanshi118**
**Thank you for opening a PR!**

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [ ] There is an informative high-level description of the changes.
+ [ ] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [ ] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [ ] The commits correspond to [relevant logical changes](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes).
+ [ ] There are tests covering the changes introduced in the PR.

Don't worry, your PR doesn't need to be in perfect order to submit it.  As development progresses and/or reviewers request changes, you can always [rewrite the history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) of your feature/PR branches.

If your PR is an ongoing effort and you would like to involve us in the process, simply make it a [draft PR](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests#draft-pull-requests).

### CODE REVIEW

**Comment by fanshi118** [comment]
The error occurred, because as we passed `plot_data[sample_col]` to `plot_split_timeseries` using `plot_timeseries_histograms` as our `plot_fn`, the twin column was no longer part of the dataframe. Scratching the parameter from the kwargs that get passed to `plot_timeseries_histograms` could prevent us from running into such error.

**Review by brandonwillard — COMMENTED** [review]
Looks like we might have a sensitive test (i.e. `test_HSStep_NegativeBinomial_sparse_shared_y`) that's failing now due to changes somewhere in the sampling process, and/or a dependency update (e.g. SciPy/NumPy) that's producing slightly different numbers.

**Review by brandonwillard — CHANGES_REQUESTED** [review]
@fanshi118, you can mark `test_HSStep_NegativeBinomial_sparse_shared_y` as `xfail` for now and create an issue for it.

**Comment by fanshi118** [comment]
> @fanshi118, you can mark `test_HSStep_NegativeBinomial_sparse_shared_y` as `xfail` for now and create an issue for it.

Done.

**Review by brandonwillard — APPROVED** [review]

**Pull request merged**
